### ISSUE TITLE
Visual Studio Hangs loading first project

### ISSUE THREAD

**Issue by chrpai** [firegiant/HeatWaveSupport#13]
### HeatWave Version

0.9.2.1

### Visual Studio Version

17.4.3

### Repro Steps

I have observed that if a sln has one project in it, I can open the solution over and over with out issues.

If a solution has more then one projects we start seeing hangs.   Doesn't matter if the project types are bundle, package or merge module or if the projects reference each other.   I've found no way to 100% prevent this.  Deleting bin/obj, .vs or %TEMP% sometimes helps but not conclusively and always.

I didn't see this in preview 1 time frame.  I don't know if it's a change in VS,  the WiX SDK project or Heatwave.

### Actual Result

VS hangs saying loading project 1 of X:  first project name.

### Expected Result

That the solution load succeeds and VS comes up.

**Comment by danlyons-softek** [comment]
In my case, as mentioned in https://github.com/wixtoolset/issues/discussions/7097#discussioncomment-4504015, I noticed that deleting the `.vs` folder next to my solution allowed Visual Studio to load my installer project without hanging.  

I narrowed the problem all the way down to the `.vs/ProjectEvaluation\<solution name>.projects.v5.2` file .  This file is generated when closing the solution gracefully.

Observations:
* If I leave the file as-is, Visual Studio will always hang when it attempts to load my installer project.
* If I delete the file or prevent its creation (e.g., kill Visual Studio rather than close it), the next time I open the solution, it loads all projects without issue.
* If I switch to a branch still using WiX 3.11 and re-generate the file on close, I can load the solution in my WiX 4 branch without issue.  
   * However, the file in question does get updated on close, causing Visual Studio to hang loading my installer project the next time I open the solution in the WiX 4 branch unless I remove it first.

**Comment by Manish082007** [comment]
@chrpai - Yes, I notice the same issue with Visual studio 17.5 Preview 2 version too.

**Comment by FireGiantHelp** [comment]
We can reproduce this internally. This issue is on our backlog to fix.

**Comment by FireGiantHelp** [comment]
We expect this issue is fixed in HeatWave v0.9.3 now available in Visual Studio Marketplace so Visual Studio should provide notification of the update.

**Comment by Manish082007** [comment]
After Updating to 0.9.3, I am no longer facing visual studio hang issue. Thank you for the fixing the issue.
