### ISSUE TITLE
Confirmation dialog when deleting preprocessor variable displays class name

### ISSUE THREAD

**Issue by jmairboeck** [firegiant/HeatWaveSupport#31]
### HeatWave Version

1.0.1.1

### Visual Studio Version

17.5.4

### Repro Steps

1. Open Project properties
2. Go to the "Build" tab
3. Click on "..." next to Preprocessor variables to edit them
4. Delete an existing one using the red "X" button

### Actual Result

The confirmation looks like this:

![grafik](https://user-images.githubusercontent.com/20295545/231793064-8dd926bc-2280-46ea-8335-5c6f0a2cc9e4.png)

### Expected Result

Instead of the class name, the name of the variable should be displayed.

**Comment by jmairboeck** [comment]
The same problem exists for Binder variables, just below.

**Comment by FireGiantHelp** [comment]
Thank you. We can reproduce this internally. This issue is on our backlog to fix.

**Comment by FireGiantHelp** [comment]
We expect this issue is fixed in [HeatWave v1.0.2 now available in Visual Studio Marketplace](https://www.firegiant.com/blog/2023/10/13/heatwave-v1.0.2-and-heatwave-build-tools-released/). Visual Studio should provide notification of the update or [you can update manually](https://www.firegiant.com/docs/heatwave/).
