### ISSUE TITLE
HeatWave 1.0.1 wouldn't install in VS 17.4.4

### ISSUE THREAD

**Issue by rseanhall** [firegiant/HeatWaveSupport#33]
### HeatWave Version

1.0.1

### What's your idea?

When trying to install HeatWave 1.0.1 in VS 17.4.4, it didn't work. The VSIX installer hung on "Initializing...". The VSIX log didn't contain anything. Restarting the machine didn't help. After upgrading to VS 17.5.4 it installed without problems. Ideally HeatWave wouldn't require the latest version of VS.

**Comment by FireGiantHelp** [comment]
HeatWave should support Visual Studio 17.0 and better. Sometimes when installing a VSIX, like HeatWave, Visual Studio will have other updates pending that are installed at the same time. The VSIXInstaller.exe does not display great UI when this happens. Perhaps updating to 17.5.4 cleared out the Visual Studio queue so that HeatWave was an easy upgrade afterwards. Being setup people, it is sometimes frustrating how little control we have over the VSIX installation experience.
