### ISSUE TITLE
Replace LibBindFiles with BindFiles when upgrading projects

### ISSUE THREAD

**Issue by jmairboeck** [firegiant/HeatWaveSupport#35]
### HeatWave Version

1.0.1.1

### What's your idea?

After upgrading library projects, the "Bind files into the library file" setting is disabled by default. This is because the property `LibBindFiles` has been renamed to `BindFiles` apparently in Wix 4. This change could be done automatically by the upgrade.

**Comment by FireGiantHelp** [comment]
This issue is on our backlog to fix.

**Comment by FireGiantHelp** [comment]
We expect this issue is fixed in [HeatWave v1.0.2 now available in Visual Studio Marketplace](https://www.firegiant.com/blog/2023/10/13/heatwave-v1.0.2-and-heatwave-build-tools-released/). Visual Studio should provide notification of the update or [you can update manually](https://www.firegiant.com/docs/heatwave/).
