### ISSUE TITLE
BindPath settings are not applied to wxproj file

### ISSUE THREAD

**Issue by Tagman** [firegiant/HeatWaveSupport#39]
### HeatWave Version

1.0.1:1

### Visual Studio Version

17.6.4

### Repro Steps

1. Open Paths tab in Properties of wixproj through Solution Explorer -> Properties (Wrench Symbol) -> Paths
2. Add Bind path to either "unnamed" or a named binder path

### Actual Result

No reference to this bind path was written into the .wxproj file. 
When reopening the project, the setting in the GUI was missing.

WiX could not locate the file referenced like this:
`<File Name="tool.exe" />` located in the directory set with bind paths.

When adding the bind path through the .wxproj file like this:
`<BindPath Include="C:\builds\tool\build\bin" />`
It did find `tool.exe`

### Expected Result

I expect the properties to be correctly written to the .wxproj file and thus being able to use files referenced in bind paths in my .wxs files.

**Comment by FireGiantHelp** [comment]
We can reproduce this internally when using the `...` browse button. This issue is on our backlog to fix.

**Comment by FireGiantHelp** [comment]
We expect this issue is fixed in [HeatWave v1.0.2 now available in Visual Studio Marketplace](https://www.firegiant.com/blog/2023/10/13/heatwave-v1.0.2-and-heatwave-build-tools-released/). Visual Studio should provide notification of the update or [you can update manually](https://www.firegiant.com/docs/heatwave/).
