### ISSUE TITLE
Not able to install Heatwave for VS 2022

### ISSUE THREAD

**Issue by kcecka42** [firegiant/HeatWaveSupport#66]
### HeatWave Version

1.0.4

### Visual Studio Version

17.6.2

### Repro Steps

1. Downloaded HeatWave for VS2022 from your site.
2. Attempted to install and it fails
[dd_VSIXInstaller_20240611083511_2a30.log](https://github.com/user-attachments/files/15804653/dd_VSIXInstaller_20240611083511_2a30.log)

### Actual Result

Failed to install.

### Expected Result

Installation work.

**Comment by Lukemtesta** [comment]
also happens in Vs2022 professional Version 17.7.3 64-bit.

This is pretty serious as its blocking our release cycle. Do you have an ETA on resolution? If not, we may have to consider removing HeatWave from our pipeline if theres no forecasted fix for the coming month ( I noticed issues have been raised in the backlog since release 2 months ago, which says to me the issue isn't high priority for the wix team? )

![image](https://github.com/firegiant/HeatWaveSupport/assets/5689501/f21685c2-8ae2-4485-9408-fa8c372efa43)

![image](https://github.com/firegiant/HeatWaveSupport/assets/5689501/61c1893e-d192-42c6-bf0a-ce8bf912c118)

**Comment by kcecka42** [comment]
I am also on a deadline to get my application deployed. Looking for an alternative.

**Comment by Lukemtesta** [comment]
@kcecka42 kcecka42 I have a work around for installing and creating templates. 

Roll back to v1.0.2:

Roll back to stable release v1.0.2 (with the template error but without installation issue).

I have a v1.0.2 from our build servers download folder but cannot attach it to the chat since its 31 MB compressed. Do you have a means for uploading it?

Creating templates: 

1) Copy the contents of a template wix4 bundle below into a .wixproj. 
2) Import the project into visual studio 2022 using the standard existing project workflow

```
<Project Sdk="WixToolset.Sdk/4.0.0">
  <PropertyGroup>
    <OutputName>WV2DeploymentWiXBurnBundleSample</OutputName>
    <OutputType>Bundle</OutputType>
    <Name>WV2DeploymentWiXBurnBundleSample</Name>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WixToolset.Util.wixext" Version="4.0.0" />
    <PackageReference Include="WixToolset.Bal.wixext" Version="4.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WV2DeploymentWiXCustomActionSample\WV2DeploymentWiXCustomActionSample.wixproj">
      <Name>WV2DeploymentWiXCustomActionSample</Name>
      <Project>{3494e3e2-cb03-4283-b8f8-e1158cdbaf3f}</Project>
      <Private>True</Private>
      <DoNotHarvest>True</DoNotHarvest>
      <RefProjectOutputGroups>Binaries;Content;Satellites</RefProjectOutputGroups>
      <RefTargetDir>INSTALLFOLDER</RefTargetDir>
    </ProjectReference>
  </ItemGroup>
</Project>
```

Outcome:

![image](https://github.com/firegiant/HeatWaveSupport/assets/5689501/a37f3062-5cae-4808-9fb0-56765209a412)

Sorry I have to mask the product names because I work in R&D and signed an NDA

**Comment by kcecka42** [comment]
@Lukemtesta , When I go to the site for version v1.0.2,  https://www.firegiant.com/blog/2023/10/13/heatwave-v1.0.2-and-heatwave-build-tools-released/ , there is a link that takes me to the same site to download the vsix that will not install.
What is the site to get an install that will work? Sorry if I am making this difficult.

**Comment by FireGiantHelp** [comment]
Search and the install log files are your friend.  You need 17.8 to install the latest HeatWave, as reported here: #64

**Comment by kcecka42** [comment]
What would be more friendly if it was stated what version is needed, other than stating Visual Studio 2022.
